services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=mysql://user:password@db:5432/mydatabase
    networks:
      - internal
    depends_on:
      - db
  db:
    image: docker.io/mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=mydatabase
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    volumes:
      - smart_garden_db_data:/var/lib/mysql
    networks:
      - internal

networks:
  internal:
    name: backend_internal_network
    external: false

volumes:
  smart_garden_db_data:
    name: smart_garden_db_data_volume
    external: false