services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # change this env var when you want a full cold rebuild:
        #   CACHEBUST=$(date +%s) docker-compose up --build -d
        CACHEBUST: ${CACHEBUST:-}
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=mysql://user:password@db:3306/mydatabase
    networks:
      - internal
    depends_on:
      - db
  db:
    image: docker.io/mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=mydatabase
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    volumes:
      - smart_garden_db_data:/var/lib/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d:ro
    networks:
      - internal
    ports:
      - 3306:3306

networks:
  internal:
    name: backend_internal_network
    external: false

volumes:
  smart_garden_db_data:
    name: smart_garden_db_data_volume
    external: false
